function addTwoNums(a,b){
    console.log(a+b)
}

addTwoNums(5, '5')

function addTwoNums(a,b){
    try{
       console.log(a+b) 
    }
    catch(err){
        console.log(err)
        
    }
    
}